CREATE TABLE IF NOT EXISTS `payment_plan_installments` (
	`id` varchar(36) NOT NULL,
	`tenant_id` varchar(36) NOT NULL,
	`plan_request_id` varchar(36) NOT NULL,
	`invoice_id` varchar(36) NOT NULL,
	`installment_number` int NOT NULL,
	`due_date` date NOT NULL,
	`amount` decimal(14,2) NOT NULL,
	`currency` varchar(10) NOT NULL DEFAULT 'INR',
	`status` enum('pending','paid','overdue') NOT NULL DEFAULT 'pending',
	`paid_at` datetime,
	`payment_transaction_id` varchar(255),
	`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `payment_plan_installments_id` PRIMARY KEY(`id`),
	CONSTRAINT `ppi_tenant_id_fk` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`) ON DELETE cascade ON UPDATE no action,
	CONSTRAINT `ppi_plan_request_id_fk` FOREIGN KEY (`plan_request_id`) REFERENCES `payment_plan_requests`(`id`) ON DELETE cascade ON UPDATE no action,
	CONSTRAINT `ppi_invoice_id_fk` FOREIGN KEY (`invoice_id`) REFERENCES `invoices`(`id`) ON DELETE cascade ON UPDATE no action,
	KEY `payment_plan_installments_tenant_idx` (`tenant_id`),
	KEY `payment_plan_installments_plan_idx` (`plan_request_id`),
	KEY `payment_plan_installments_invoice_idx` (`invoice_id`)
);
