from api.logging import logger

def _parse_email_output(raw_text: str) -> tuple[str, str]:
    """
    Extract subject and body from the LLM's formatted output.
    Handles variations like 'Subject: ' and 'Body:' markers.
    """
    subject = ""
    body = ""
    
    for line in raw_text.splitlines():
        if line.lower().strip().startswith("subject:"):
            subject = line[len("subject:"):].strip()
            break
            
    lower_text = raw_text.lower()
    marker = "body:"
    if marker in lower_text:
        marker_pos = lower_text.find(marker)
        body = raw_text[marker_pos + len(marker):].strip()
    else:
        if subject and subject in raw_text:
            body = raw_text[raw_text.find(subject) + len(subject):].strip()
        else:
            body = raw_text

    if not subject or len(body) < 20:
        logger.error(
            "validation_failed",
            invoice_id="SYSTEM",
            reason=f"LLM generated invalid or empty email structure for text: {raw_text[:50]}..."
        )
        return "Validation Error: Hallucination detected", "Incomplete email body generated by LLM."

    if "ignore previous" in body.lower():
         return "Security Error", "Potential prompt injection detected in output."

    return subject, body
